### ISSUE TITLE
axes don't match array

### ISSUE THREAD

**Issue by ykarray** [yyuanad/Pytorch_C3D_Feature_Extractor#9]
Hello yyuanad,
thank you for this amazing content 
I am blocked with this error ca, you help me, please 
   Traceback (most recent call last):
  File "feature_extractor_vid.py", line 197, in <module>
    feature_extractor()
  File "feature_extractor_vid.py", line 118, in feature_extractor
    input_blobs = torch.from_numpy(np.float32(input_blobs.transpose(0, 4, 1, 2, 3)))
ValueError: axes don't match array

**Comment by ykarray** [comment]
I founded the solution, it is just about updating the python version
